language: node_js
node_js: 
- "0.10"
env: 
  global:
  - secure: Q8cycieWbsrx5/rE5bgFsujIV2s+GkVPlUll1IOw0YwSV/dLZTtf/0QWdQwANCcL2knF7VRI8VoP9duMCRotLkH+9wgqpRNHAZSaRYWt0DD9znCjBgA5BDn7Nq7P/DTfy8PZgOye2KsYOWHFQveF81eKLQguopOXBhq4hVgAZc4=
  - secure: hK2WqaUMU5Wdsl3mrBWemteuLr6JcubRGUcXTvEZV1gtx4ksKm9P61/DQZeyY1FbFVBA4739dr0fjioACmnEdG5H+IHbliyW6qXpCnWx/BwP+izzIcoN1hS2OGvEHwr4eyTn6s/Sd1abx6lbxmqFTEQPKnfw0j08aEEPRm0oeWA=
addons: 
  sauce_connect: true
before_install: 
- npm install -g grunt-cli
